quantdo:
  #Quantdo SSO配置(依赖于Redis缓存配置).
  sso:
    generic:
      rest:
        # SSO是否启用针对"通用网关"的服务鉴权（默认为否）
        needcheckpermission: false
    session:
      #单位是毫秒，shiro做会话时长设置.
      timeout: 3600000
    #缓存登录用户认证信息开关,默认为false
    #authentication-caching-enabled: true
    #缓存登录用户授权权限信息开关,默认为false
    #authorization-caching-enabled: true
    #web前端按钮关联的后端服务访问控制开关,默认为false
    button-service-access-control-enabled: false
    #SSO用户登录界面Url(需要项目组定制界面,并部署到nginx下)
    #loginUrl: /sso/login
    # SSO用户登录成功后界面Url(需要项目组定制界面,并部署到nginx下)
    #successUrl: /sso/success
    # SSO用户未授权访问时重定向界面Url(需要项目组定制界面,并部署到nginx下).
      #unauthorizedUrl: /sso/unauth
    #kickout:
      # SSO是否开启"踢出"功能(默认不开启)
      #enabled: true
      # SSO用户""踢出"方式,true表示相同终端类型只保持最后一个登录会话,false表示只允许maxSession规定的最大会话数(超出将被自动"踢出")
      #byTerminal: true
      # SSO用户""踢出"方式byTerminal为false时该设置项才生效,超出maxSession规定的会话数将被自动"踢出"
      #maxSession: 1
      # SSO用户""踢出"方式byTerminal为false时该设置项才生效,kickoutAfter为true表示踢出之前登录的,kickoutAfter为false表示踢出之后登录的。
      #kickoutAfter: true
    #SSO客制化访问路径权限定义列表.
    custom-acl-definitions:
    #shiro用户登录与权限数据查询定义.
    - user_type: default
      dataSource: master
      system_id: 7
      #SSO需要系统需要授权访问的全部资源(如:菜单资源、Rest服务资源、Service、按钮资源等)
      #  system_acl_query: select res, acl from sso_resource_acl
      # 根据登录名获取SSO内置用户模型的查询SQL语句.
      # user_info_query: select id,username,loginname,password,pwd_salt,pwd_algorithm from sso_user where loginname=?
      # 查询对应登录用户ID的角色信息SQL语句.
      # user_role_query: select user_id,role from sso_role where user_id=?
      # 查询对应登录用户ID的权限信息SQL语句.
    #  user_perm_query: select user_id, perm from sso_perm where user_id=?
    #SSO客制化访问路径权限定义列表.
    custom-path-definitions:
    #shiro放开swagger2访问权限.
    - resource: /swagger-resources/**
      access-control: anon
    - resource: /v2/api-docs
      access-control: anon
    - resource: /v2/api-docs-ext
      access-control: anon
    - resource: /doc.html
      access-control: anon
    - resource: /webjars/**
      access-control: anon
    #SSO测试验证拓展接口.
    - resource: /sso/demo/login2
      access-control: anon
    #- resource: /sso/demo/add
    #  access-control: roles[100002],perms[ADD],hasAnyRole[admin],hasAnyPerm["menu:create:*"]