management:
  #dubbo服务监听接口
  port: 8888

#指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
dubbo:
  application:
    name: dubbo-digital-consumer
  consumer:
    filter: dubboUserBindingFilter
    #统一设置服务提供方的规则
    timeout: 5000
    check: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  #指定注册中心的位置
  registry:
    id: zk-consumer-registry
    protocol: zookeeper
    address: zookeeper://192.168.1.21:2181
    #address: 192.168.100.166:2181,192.168.100.167:2181,192.168.100.168:2181

#服务接口版本号
service:
  version: 1.0.0