spring:
  ##Druid DataSource数据库访问配置
  datasource:
    is-dynamic-datasource: true
    type: com.alibaba.druid.pool.DruidDataSource
    #压力测试环境
    #url: jdbc:mysql://192.168.100.167/sso?characterEncoding=utf-8
    #username: root
    #password: root
    url: jdbc:mysql://192.168.1.22:3306/security?characterEncoding=utf-8&amp;autoReconnect=true&amp;useSSL=false
    username: trader
    password: js2018
    driver-class-name: com.mysql.jdbc.Driver
    #连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #连接等待超时时间
    maxWait: 60000
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    timeBetweenEvictionRunsMillis: 60000
    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
    #由于log4j换成了log4j2,此处filters中的log4j也相应换成log4j2,不然会报错
    filters: stat,wall,log4j2
    logSlowSql: true
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count==countSql;pageNum=pageNum;pageSize=pageSize;