spring:
  #Redis缓存配置(RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    #database: 0
    # Redis服务器地址
    host: 192.168.1.22
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password: 123456
    # 连接超时时间（毫秒）
    timeout: 2000
    #redis pool配置
    lettuce:
      pool:
        max-active: 10
        max-wait: 3000
        max-idle: 10
        min-idle: 0
    #redis cluster
    #集群节点host:port,多个节点逗号分隔
    # cluster:
    #  nodes: 192.168.100.166:6379,192.168.100.166:6380,192.168.100.167:6379,192.168.100.167:6380,192.168.100.168:6379,192.168.100.168:6380
    #  maxRedirects: 3

  #缓存实例列表(全局设置)
  cache:
    cache-names: customRealm.authenticationCache,customRealm.authorizationCache,shiro-activeSessionCache,userIdCache
    multi:
      caffeine:
        #是否启用一级缓存,默认为不开启.
        enabled: false
        ##Caffeine全局访问后过期时间，单位毫秒.
        defaultExpireAfterAccess: 60000
        ##Caffeine全局初始化大小.
        defaultInitialCapacity: 5000
        ##Caffeine全局最大缓存对象个数，超过此数量时之前放入的缓存将失效.
        defaultMaximumSize: 10000
        ##Caffeine全局访问后过期时间，单位毫秒.
        expireAfterAccess:
          customRealm.authenticationCache: 60000
          customRealm.authorizationCache: 60000
          shiro-activeSessionCache: 60000
          userIdCache: 60000
        ##Caffeine全局初始化大小.
        initialCapacity:
          customRealm.authenticationCache: 5000
          customRealm.authorizationCache: 5000
          shiro-activeSessionCache: 5000
          userIdCache: 60000
        ##Caffeine全局最大缓存对象个数，超过此数量时之前放入的缓存将失效.
        maximumSize:
          customRealm.authenticationCache: 10000
          customRealm.authorizationCache: 10000
          shiro-activeSessionCache: 10000
          userIdCache: 10000

      ##Redis全局过期时间，单位毫秒，默认不过期.
      redis:
        defaultExpire: 7200000
        ##缓存实例列表(针对缓存实例设置,缓存实例可以不单独设置)
        ##Redis缓存过期时间设置，单位毫秒.
        expire:
          customRealm.authenticationCache: 1800000
          customRealm.authorizationCache: 1800000
          shiro-activeSessionCache: 1800000
          userIdCache: 1800000
